### ISSUE TITLE
Openfire Cluster Issue

### ISSUE THREAD

**Issue by ernakulgoyal** [igniterealtime/openfire-chat#8]
I am unable to start openfire cluster after I installed this plugin in openfire on all the cluster nodes.

Can you please suggest what additional step I have to perform? I am using **Openfire Server Version - 4.3.1** and **plugin version - 0.9.4 Release 9**.

Can someone suggest a way out here?

**Comment by ernakulgoyal** [comment]
@bsherman @deleolajide @akrherz @dwd Stuck in setting up a cluster after installing this plugin, please suggest here.

**Comment by guusdk** [comment]
This issue gets under my skin - not because of the problem that's reported, but the manner in which it is reported.

Firstly, you offer hardly any information that we can use to diagnose the problem, other than version numbers and "it does not work". I wonder what your thought process is: How do you expect us to solve an issue that we know nothing about?

Secondly, I'm appalled by people needing to explicitly mention people, only to claim more attention. The fact that you're mentioning people that have no involvement in the development of this project suggests that you're just shooting with buckshot here. That's just spam, in my book. You don't appear to care who you annoy with pointless messages, as long as you get attention.

And, lastly, you're raising a Github issue, which is not the way to request help (it is used to report bugs or feature requests). We have a perfectly good venue for support at https://discourse.igniterealtime.org/

The Ignite Realtime community is always happy to try and help people, but it's good to remember that we're all just people volunteering our spare time. Issues like these drain motivation.

**Comment by ernakulgoyal** [comment]
@guusdk How could I offer any information on the issue when I don't have it in logs itself (after enabling debug logs), just receiving an error message when I started the cluster.

I was not receiving any inputs from the community, you already closed the issue without knowing the concern.

For pointing you guys on this pointless issue/message, there are other open items which haven't been responded for so long, didn't intended to drain your motivation at all.
